
- block:
  - name: Download drone-cli
    get_url:
      url: http://downloads.drone.io/release/darwin/amd64/drone.tar.gz
      mode: u=rwx,g=rx,o=rx
      dest: /opt/drone.tar.gz

  - name: Install drone-cli
    unarchive:
      copy: no
      src: /opt/drone.tar.gz
      dest: /usr/bin
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx


  # - name: Pull drone server image
  #   debug: msg=Not Implemented

  # - name: Pull drone agent image
  #   debug: msg=Not Implemented

  # # Use environment variables
  # - name: Start drone server
  #   debug: msg=Not Implemented

  # - name: Start drone agent
  #   debug: msg=Not Implemented
